[package]
name    = "drone-activitypub"
version = "2.0.0"
authors = ["zentauro <pedrogomezmartin1999@gmail.com>"]
edition = "2018"

[dependencies.elefren]
version     = "0.16.0"
features    = ["json"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
